# Generated by Django 4.0 on 2023-10-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='libro',
            new_name='calzados',
        ),
    ]
