# Generated by Django 4.0 on 2023-10-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calzados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzados',
            name='imagen',
            field=models.ImageField(blank=True, default='calzados/calzados_default.png', null=True, upload_to='calzados'),
        ),
    ]
